<?php

use Illuminate\Database\Seeder;

class ModelCompetencesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('model_competences')->insert([
            ['name'=> 'Para Colegio',
            'description'=> 'Modelo para colegio'],
            ['name'=> 'Para Universidad',
            'description'=> 'Modelo para universidad'],
            ['name'=> 'Para Trabajo',
            'description'=> 'Modelo para trabajo']
        ]);

        DB::table('competences')->insert([
            ['name'=> 'comp1',
            'label' => 'Comp 1',
            'description'=> 'Modelo para colegio',
            'model_competences_id' => 1,
            'competence_type_id' => 1],
            ['name'=> 'comp2',
            'label' => 'comp2',
            'description'=> 'Modelo para colegio',
            'model_competences_id' => 1,
            'competence_type_id' => 1],
            ['name'=> 'comp3',
            'label' => 'comp3',
            'description'=> 'Modelo comp3',
            'model_competences_id' => 1,
            'competence_type_id' => 1],
            ['name'=> 'comp4',
            'label' => 'comp4',
            'description'=> 'Modelo comp4',
            'model_competences_id' => 1,
            'competence_type_id' => 1],
            ['name'=> 'comp5',
            'label' => 'comp5',
            'description'=> 'Modelo comp5',
            'model_competences_id' => 1,
            'competence_type_id' => 2],
            ['name'=> 'comp6',
            'label' => 'comp6',
            'description'=> 'Modelo comp6',
            'model_competences_id' => 1,
            'competence_type_id' => 2],
            ['name'=> 'comp7',
            'label' => 'comp7',
            'description'=> 'Modelo comp7',
            'model_competences_id' => 1,
            'competence_type_id' => 2],
            ['name'=> 'comp8',
            'label' => 'comp8',
            'description'=> 'Modelo comp8',
            'model_competences_id' => 1,
            'competence_type_id' => 2],
            ['name'=> 'comp1-1',
            'label' => 'Comp 1',
            'description'=> 'Modelo para colegio',
            'model_competences_id' => 2,
            'competence_type_id' => 1],
            ['name'=> 'comp2-1',
            'label' => 'comp2',
            'description'=> 'Modelo para colegio',
            'model_competences_id' => 2,
            'competence_type_id' => 1],
            ['name'=> 'comp3-1',
            'label' => 'comp3',
            'description'=> 'Modelo comp3',
            'model_competences_id' => 2,
            'competence_type_id' => 1],
            ['name'=> 'comp4-1',
            'label' => 'comp4',
            'description'=> 'Modelo comp4',
            'model_competences_id' => 2,
            'competence_type_id' => 1],
            ['name'=> 'comp5-1',
            'label' => 'comp5',
            'description'=> 'Modelo comp5',
            'model_competences_id' => 2,
            'competence_type_id' => 2],
            ['name'=> 'comp6-1',
            'label' => 'comp6',
            'description'=> 'Modelo comp6',
            'model_competences_id' => 2,
            'competence_type_id' => 2],
            ['name'=> 'comp7-1',
            'label' => 'comp7',
            'description'=> 'Modelo comp7',
            'model_competences_id' => 2,
            'competence_type_id' => 2],
            ['name'=> 'comp8-1',
            'label' => 'comp8',
            'description'=> 'Modelo comp8',
            'model_competences_id' => 2,
            'competence_type_id' => 2]

        ]);

        DB::table('competence_levels')->insert([
            ['technical_description'=> 'technical_description 1',
            'amicable_description' => 'amicable_description 1',
            'report_description' => 'report_description 1',
            'level'=> 1,
            'competence_id' => 1,
            ],
            ['technical_description'=> 'technical_description 2',
            'amicable_description' => 'amicable_description 2',
            'report_description' => 'report_description 2',
            'level'=> 2,
            'competence_id' => 1,
            ],
            ['technical_description'=> 'technical_description 3',
            'amicable_description' => 'amicable_description 3',
            'report_description' => 'report_description 3',
            'level'=> 3,
            'competence_id' => 1,
            ],
            ['technical_description'=> 'technical_description 4',
            'amicable_description' => 'amicable_description 4',
            'report_description' => 'report_description 4',
            'level'=> 4,
            'competence_id' => 1,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'report_description' => 'reportes',
            'level'=> 1,
            'competence_id' => 2,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 2,
            'competence_id' => 2,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 3,
            'competence_id' => 2,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 4,
            'competence_id' => 2,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 1,
            'competence_id' => 3,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 2,
            'competence_id' => 3,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 3,
            'competence_id' => 3,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 4,
            'competence_id' => 3,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 1,
            'competence_id' => 4,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 2,
            'competence_id' => 4,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 3,
            'competence_id' => 4,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 4,
            'competence_id' => 4,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 1,
            'competence_id' => 5,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 2,
            'competence_id' => 5,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 3,
            'competence_id' => 5,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 4,
            'competence_id' => 5,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 1,
            'competence_id' => 6,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 2,
            'competence_id' => 6,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 3,
            'competence_id' => 6,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 4,
            'competence_id' => 6,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 1,
            'competence_id' => 7,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 2,
            'competence_id' => 7,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 3,
            'competence_id' => 7,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 4,
            'competence_id' => 7,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 1,
            'competence_id' => 8,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 2,
            'competence_id' => 8,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 3,
            'competence_id' => 8,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 4,
            'competence_id' => 8,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 1,
            'competence_id' => 9,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 2,
            'competence_id' => 9,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 3,
            'competence_id' => 9,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 4,
            'competence_id' => 9,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 1,
            'competence_id' => 10,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 2,
            'competence_id' => 10,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 3,
            'competence_id' => 10,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 4,
            'competence_id' => 10,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 1,
            'competence_id' => 11,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 2,
            'competence_id' => 11,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 3,
            'competence_id' => 11,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 4,
            'competence_id' => 11,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 1,
            'competence_id' => 12,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 2,
            'competence_id' => 12,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 3,
            'competence_id' => 12,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 4,
            'competence_id' => 12,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 1,
            'competence_id' => 13,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 2,
            'competence_id' => 13,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 3,
            'competence_id' => 13,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 4,
            'competence_id' => 13,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 1,
            'competence_id' => 14,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 2,
            'competence_id' => 14,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 3,
            'competence_id' => 14,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 4,
            'competence_id' => 14,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 1,
            'competence_id' => 15,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 2,
            'competence_id' => 15,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 3,
            'competence_id' => 15,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 4,
            'competence_id' => 15,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 1,
            'competence_id' => 16,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 2,
            'competence_id' => 16,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 3,
            'competence_id' => 16,
            ],
            ['technical_description'=> 'tecdes',
            'amicable_description' => 'amicdes',
            'report_description' => 'reportes',
            'level'=> 4,
            'competence_id' => 16,
            ]
        ]);

      DB::table('interventions')->insert([
            ['title' => 'Intervencion para el colegio Santisteban',
            'description'=> 'Intervencion para el colegio Santisteban',
            'welcome_text'=> 'Texto de Bievenida',
            'introduction' => 'Texto de introduccion',
            'case_introduction'=> 'Texto de introduccion al caso',
            'final_text'=> 'Texto final',
            'support_mail'=> 'mailito@mail.com',
            'model_competences_id' => 1,
            'enabled'=> true]
        ]);
    }
}
